[server]
headless = true
maxUploadSize = 20

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#10B981"
backgroundColor = "#08111F"
secondaryBackgroundColor = "#111827"
textColor = "#F8FAFC"
font = "sans serif"
